import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Layout from "@/components/layout";
import Logo from "@/image/icons/logo.svg";
import { useRouter } from "next/router";
import { getReadPrivacy } from '@/utils/storeTool'

export default function Home() {
  const router = useRouter();

  useEffect(() => {
    const isRead = getReadPrivacy();
    (!isRead) ? router.push("/auth/privacy-term") : router.push("/cpop/station-map");
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}

Home.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};
